---
- name: Setup the Master Node
  hosts: oceannik_master
  gather_facts: yes
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: Update apt cache if needed
      apt:
        update_cache: yes
        cache_valid_time: 3600
      ignore_errors: yes

  tasks:
    - name: Install required packages
      tags: packages
      block:
        - name: Install required packages
          apt:
            name:
              # Useful for debugging and more
              - cron
              - vim
              - jq
              - tree
              - curl
              # Required by other programs
              - build-essential
              - bzip2
              - libssl-dev
              - policykit-1
              - python3
              - python3-pip
            state: present

        - name: Install commonly used Python packages
          pip:
            name:
              - setuptools
              - wheel

    - name: Set up Docker
      tags: docker
      block:
        - name: Check whether Docker is installed
          command: docker -v
          register: docker_version_check
          ignore_errors: True

        - name: Ensure docker and docker-py packages are absent
          pip:
            name:
              - docker-py
              - docker
            state: absent
          when: docker_version_check is failed

        - name: Install the correct python Docker package
          pip:
            name: docker
            state: present

        - name: Install Docker
          apt:
            name: docker.io
            state: present
          when: docker_version_check is failed

        - name: Install docker-compose
          pip:
            name: docker-compose
            state: present

        - name: Start the Docker service
          service:
            name: docker
            state: started
            enabled: yes

    - name: Set up nginx
      tags: nginx
      block:
        - name: Install nginx
          apt:
            name: nginx
            state: present

        - name: Start the nginx service
          service:
            name: nginx
            state: started
